### ISSUE TITLE
请问测试集跑出来为什么准确率是0.78？

### ISSUE THREAD

**Issue by fenzi1223** [Acstream/Dilated-Block-Based-Convolutional-Network#1]

**Comment by Acstream** [comment]
我这里跑出的dbcn结果如下
Start Testing DBCN!
Building DBCN model!
residual convolution:Tensor("residual_convolution/stack:0", shape=(?, 4, 56, 4), dtype=float32)
dilated block 1:Tensor("dilated_block_1/stack:0", shape=(?, 16, 56, 6), dtype=float32)
dilated block 2:Tensor("dilated_block_2/stack:0", shape=(?, 4, 56, 4), dtype=float32)
concat:Tensor("concat_pool_flat_output/concat:0", shape=(?, 8, 56, 4), dtype=float32)
pooling:Tensor("concat_pool_flat_output/MaxPool:0", shape=(?, 1, 56, 4), dtype=float32)
flat:Tensor("concat_pool_flat_output/Flatten/flatten/Reshape:0", shape=(?, 224), dtype=float32)
dropout:Tensor("concat_pool_flat_output/dropout/cond/Merge:0", shape=(?, 224), dtype=float32)
dense:Tensor("concat_pool_flat_output/dense/Tanh:0", shape=(?, 2), dtype=float32)
Loading model completed!
Getting Test Data!
Shape:
testX shape:(154, 20, 56)
testY shape:(154, 2)
TP number=64
FN number=13
TN number=55
FP number=22
Precision_R=TP/(TP+FP)=0.744186047
Precision_NR=TN/(TN+FN)=0.808823529
Recall_R=TP/(TP+FN)=0.831168831
Recall_NR=TN/(TN+FP)=0.714285714
F1_R=2*Precision_R*Recall_R/(Precision_R+Recall_R)=0.785276074
F1_NR=2*Precision_NR*Recall_NR/(Precision_NR+Recall_NR)=0.758620690
F1_AVG=(F1_R+F1_NR)/2=0.771948382
Accuracy=(TP+TN)/(TP+TN+FP+FN)=0.772727273
DBCN Test Completed!
